# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'fgrehm/trusty64-lxc'

  config.vm.hostname = 'dev'
  config.vm.network "forwarded_port", guest: 80, host: 8000

  config.vm.provision :shell, inline: 'sudo apt-get install -y redir'

  config.vm.synced_folder 'app', '/home/vagrant/app'
  config.vm.synced_folder 'database', '/home/vagrant/database'
  config.vm.synced_folder 'salt/roots', '/srv'

  config.ssh.forward_agent = true

  config.vm.provision :salt do |salt|
    salt.minion_config = 'salt/minion.conf'
    salt.run_highstate = true
    salt.verbose = true
  end
end
