# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/precise32'

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--name', 'dev']
    v.customize ['modifyvm', :id, '--memory', 1024]
  end

  config.vm.hostname = 'dev'

  config.vm.network :private_network, ip: '192.168.10.33'

  config.vm.synced_folder '..', '/home/vagrant/code'
  config.vm.synced_folder 'salt/roots', '/srv'

  config.vm.provision :salt do |salt|
    salt.minion_config = 'salt/minion.conf'
    salt.run_highstate = true
    salt.verbose = true
  end
end
